# 100 numpy exercises

This is a collection of exercises that have been collected in the numpy mailing list, on stack overflow
and in the numpy documentation. The goal of this collection is to offer a quick reference for both old
and new users but also to provide a set of exercises for those who teach.


If you find an error or think you've a better way to solve some of them, feel
free to open an issue at <https://github.com/rougier/numpy-100>.

File automatically generated. See the documentation to update questions/answers/hints programmatically.

Run the `initialize.py` module, then for each question you can query the
answer or an hint with `hint(n)` or `answer(n)` for `n` question number.

In [1]:
%run initialise.py

ModuleNotFoundError: No module named 'mdutils'

#### 1. Import the numpy package under the name `np` (★☆☆)

In [2]:
import numpy as np

#### 2. Print the numpy version and the configuration (★☆☆)

In [11]:
print(np.version)
print(np.__version__)

<module 'numpy.version' from 'C:\\Users\\sbuer\\Anaconda3\\lib\\site-packages\\numpy\\version.py'>
1.18.1


#### 3. Create a null vector of size 10 (★☆☆)

In [13]:
nullVect = np.zeros([10])
print(nullVect)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


#### 4. How to find the memory size of any array (★☆☆)

In [15]:
def memorySize(a):
    return a.size * a.itemsize

print(memorySize(nullVect))

80


#### 5. How to get the documentation of the numpy add function from the command line? (★☆☆)

In [16]:
help(np.add)

Help on ufunc object:

add = class ufunc(builtins.object)
 |  Functions that operate element by element on whole arrays.
 |  
 |  To see the documentation for a specific ufunc, use `info`.  For
 |  example, ``np.info(np.sin)``.  Because ufuncs are written in C
 |  (for speed) and linked into Python with NumPy's ufunc facility,
 |  Python's help() function finds this page whenever help() is called
 |  on a ufunc.
 |  
 |  A detailed explanation of ufuncs can be found in the docs for :ref:`ufuncs`.
 |  
 |  Calling ufuncs:
 |  ===============
 |  
 |  op(*x[, out], where=True, **kwargs)
 |  Apply `op` to the arguments `*x` elementwise, broadcasting the arguments.
 |  
 |  The broadcasting rules are:
 |  
 |  * Dimensions of length 1 may be prepended to either array.
 |  * Arrays may be repeated along dimensions of length 1.
 |  
 |  Parameters
 |  ----------
 |  *x : array_like
 |      Input arrays.
 |  out : ndarray, None, or tuple of ndarray and None, optional
 |      Alternate array o

#### 6. Create a null vector of size 10 but the fifth value which is 1 (★☆☆)

In [19]:
v = np.zeros([10])
v[5-1] = 1
print(v)

[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


#### 7. Create a vector with values ranging from 10 to 49 (★☆☆)

In [23]:
v = np.arange(10,49+1,1)
print(v)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


#### 8. Reverse a vector (first element becomes last) (★☆☆)

In [30]:
np.flip(v)

array([49, 48, 47, 46, 45, 44, 43, 42, 41, 40, 39, 38, 37, 36, 35, 34, 33,
       32, 31, 30, 29, 28, 27, 26, 25, 24, 23, 22, 21, 20, 19, 18, 17, 16,
       15, 14, 13, 12, 11, 10])

#### 9. Create a 3x3 matrix with values ranging from 0 to 8 (★☆☆)

In [38]:
m = np.arange(0,8+1,1).reshape(3,3)
print(m)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


#### 10. Find indices of non-zero elements from [1,2,0,0,4,0] (★☆☆)

In [40]:
v = np.array([1,2,0,0,4,0])
print(v > 0)

[ True  True False False  True False]


#### 11. Create a 3x3 identity matrix (★☆☆)

In [41]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

#### 12. Create a 3x3x3 array with random values (★☆☆)

In [42]:
np.random.rand(3,3,3)

array([[[3.69344074e-01, 4.01416913e-01, 5.53844122e-01],
        [1.48841759e-01, 6.37564784e-01, 1.39037677e-01],
        [8.15587584e-01, 4.44663585e-01, 6.88663064e-02]],

       [[2.93739099e-01, 6.67099490e-01, 6.89159370e-01],
        [5.41586001e-01, 6.60485130e-01, 4.51592897e-01],
        [2.75652631e-01, 9.53771475e-01, 3.80506107e-01]],

       [[1.65835188e-01, 2.77033061e-01, 9.01032211e-01],
        [2.15222553e-02, 6.30658589e-01, 8.16578109e-01],
        [2.23174551e-02, 4.70748281e-04, 9.73177482e-01]]])

#### 13. Create a 10x10 array with random values and find the minimum and maximum values (★☆☆)

In [43]:
A = np.random.rand(10,10)
print(A.min(), A.max())

0.015297841041201465 0.9835632436818191


#### 14. Create a random vector of size 30 and find the mean value (★☆☆)

In [45]:
v = np.random.rand(30)
print(len(v))
v.mean()

30


0.5375601188007532

#### 15. Create a 2d array with 1 on the border and 0 inside (★☆☆)

In [48]:
A = np.ones([3,3])
A[1,1] = 0
print(A)

[[1. 1. 1.]
 [1. 0. 1.]
 [1. 1. 1.]]


#### 16. How to add a border (filled with 0's) around an existing array? (★☆☆)

In [56]:
np.pad(A, 1)

array([[0., 0., 0., 0., 0.],
       [0., 1., 1., 1., 0.],
       [0., 1., 0., 1., 0.],
       [0., 1., 1., 1., 0.],
       [0., 0., 0., 0., 0.]])

#### 17. What is the result of the following expression? (★☆☆)
```python
0 * np.nan
np.nan == np.nan
np.inf > np.nan
np.nan - np.nan
np.nan in set([np.nan])
0.3 == 3 * 0.1
```

In [64]:
0.3 == 3*0.1

False

#### 18. Create a 5x5 matrix with values 1,2,3,4 just below the diagonal (★☆☆)

In [97]:
A = np.arange(1,26).reshape(5,5)
print('Original matrix')
print(A)
print("Sliced bit so main diagonal is the one below the actual main diagonal")
print(A[1:,:])
## fill_diagonal only works on the main diagonal, 
## but I can slice to get the diagonal I want
np.fill_diagonal(A[1:,:], np.arange(1,5))  
print("Matrix with values 1,2,3,4 in diagonal below main diagonal")
print(A)

Original matrix
[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]]
Sliced bit so main diagonal is the one below the actual main diagonal
[[ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]]
Matrix with values 1,2,3,4 in diagonal below main diagonal
[[ 1  2  3  4  5]
 [ 1  7  8  9 10]
 [11  2 13 14 15]
 [16 17  3 19 20]
 [21 22 23  4 25]]


#### 19. Create a 8x8 matrix and fill it with a checkerboard pattern (★☆☆)

In [119]:
# create a tiny chessboard (2x2) and repeat pattern to scale up to 8x8
chessboard = np.tile(np.array([[0,1], [1,0]]), (int(8/2), int(8/2)))
print(chessboard)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


#### 20. Consider a (6,7,8) shape array, what is the index (x,y,z) of the 100th element?

In [138]:
A = np.random.rand(6,7,8)
print(A[0:3,0,0])
print(A[1,0,0])
print(A.shape)
print(np.where(A == A.flatten()[100-1]))
print(A.flatten()[100-1])
A[1,5,3]

[0.16847074 0.76672856 0.67629762]
0.7667285627777592
(6, 7, 8)
(array([1], dtype=int64), array([5], dtype=int64), array([3], dtype=int64))
0.3579069302479607


0.3579069302479607

#### 21. Create a checkerboard 8x8 matrix using the tile function (★☆☆)

In [125]:
# see 19.:
chessboard = np.tile(np.array([[0,1], [1,0]]), (int(8/2), int(8/2)))
print(chessboard)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


#### 22. Normalize a 5x5 random matrix (★☆☆)

In [170]:
A = np.random.randint(0,10,(5,5))
print("original matrix")
print(A)
Anorm = A / A.sum(axis=1)[:,np.newaxis]
print("normalized matrix (here that means the row vectors sum to 1)")
print(Anorm)
print("verify row sums")
print(Anorm.sum(axis=1))

original matrix
[[6 7 7 8 6]
 [1 4 6 7 9]
 [9 3 5 8 5]
 [0 1 6 8 6]
 [3 6 3 2 2]]
normalized matrix (here that means the row vectors sum to 1)
[[0.17647059 0.20588235 0.20588235 0.23529412 0.17647059]
 [0.03703704 0.14814815 0.22222222 0.25925926 0.33333333]
 [0.3        0.1        0.16666667 0.26666667 0.16666667]
 [0.         0.04761905 0.28571429 0.38095238 0.28571429]
 [0.1875     0.375      0.1875     0.125      0.125     ]]
verify row sums
[1. 1. 1. 1. 1.]


#### 23. Create a custom dtype that describes a color as four unsigned bytes (RGBA) (★☆☆)

In [376]:
dtcol = np.dtype([('R','u1'), ('G','u1'), ('B','u1'), ('A','u1')])
dtcol

dtype([('R', 'u1'), ('G', 'u1'), ('B', 'u1'), ('A', 'u1')])

#### 24. Multiply a 5x3 matrix by a 3x2 matrix (real matrix product) (★☆☆)

In [187]:
A = np.random.randint(0,10,(5,3))
print(A)
B = np.random.randint(0,10,(3,2))
print(" ")
print(B)
C = A @ B
print(" ")
print(C)

[[5 0 4]
 [8 8 1]
 [8 3 3]
 [8 4 4]
 [8 7 0]]
 
[[3 2]
 [4 1]
 [5 9]]
 
[[35 46]
 [61 33]
 [51 46]
 [60 56]
 [52 23]]


#### 25. Given a 1D array, negate all elements which are between 3 and 8, in place. (★☆☆)

In [220]:
A = np.random.randint(0,10,(10))
print(A)
A = np.negative(A, where=[(A>3) & (A<9)])
print(A)

[3 6 6 5 3 9 4 7 0 3]
[[ 2 -6 -6 -5  5  7 -4 -7  8  3]]


#### 26. What is the output of the following script? (★☆☆)
```python
# Author: Jake VanderPlas

print(sum(range(5),-1))
from numpy import *
print(sum(range(5),-1))
```

In [224]:
print(sum(range(5),-1))
from numpy import *
print(sum(range(5),-1))

10
10


#### 27. Consider an integer vector Z, which of these expressions are legal? (★☆☆)
```python
Z**Z
2 << Z >> 2
Z <- Z
1j*Z
Z/1/1
Z<Z>Z
```

In [234]:
Z = 2
# 1 is z to the power of z, legal
Z**Z

# 2 is odd, not sure what that does, I'd think illegal
2 << Z >> 2 # no error, so apprently legal, what does it do though?

# 3 looks like R syntax, probably illegal
Z <- Z # Ah of course, it is simply smaller than minus Z

# 4 is legal, because 1j is creating a complex number
1j*Z

# 5 is legal, simply dividing by 1 twice
Z/1/1

# 6 is odd to do, but should be legal
Z<Z>Z

False

#### 28. What are the result of the following expressions?
```python
np.array(0) / np.array(0)
np.array(0) // np.array(0)
np.array([np.nan]).astype(int).astype(float)
```

In [244]:
# 1. nan, has no element in array, cannot divide
np.array(0) / np.array(0) # floating point division

# 2. 
np.array(0) // np.array(0) # integer division

# 3. Why does casting nan as an integer create a large negative integer????
np.array([np.nan]).astype(int).astype(float)

C:\Users\sbuer\Anaconda3\lib\site-packages\ipykernel_launcher.py:2: RuntimeWarning: invalid value encountered in true_divide
  
C:\Users\sbuer\Anaconda3\lib\site-packages\ipykernel_launcher.py:5: RuntimeWarning: divide by zero encountered in floor_divide
  """


array([-2147483648])

#### 29. How to round away from zero a float array ? (★☆☆)

In [252]:
A = np.random.rand(5,5) * 2 - 1
print(A)
print(np.sign(A) * np.ceil(np.abs(A)))

[[-0.91432757  0.04054543 -0.09430452 -0.5989747   0.89815426]
 [ 0.66900335 -0.27512054  0.93962096 -0.9537501   0.38167974]
 [-0.59199406  0.37450945 -0.60099631 -0.07509074 -0.8243675 ]
 [-0.51254442  0.81876108  0.12145692 -0.71704226  0.6616377 ]
 [ 0.00126259 -0.2853047   0.99635636 -0.16746719 -0.49419439]]
[[-1.  1. -1. -1.  1.]
 [ 1. -1.  1. -1.  1.]
 [-1.  1. -1. -1. -1.]
 [-1.  1.  1. -1.  1.]
 [ 1. -1.  1. -1. -1.]]


#### 30. How to find common values between two arrays? (★☆☆)

In [263]:
A = np.random.randint(0,5,(5,5))
print(A)
print(" ")
B = np.random.randint(0,5,(5,5))
print(B)
print(" ")
print(A == B)
print(" ")
print(A[A == B])
common_values = np.unique(A[A == B])
print(" ")
print(common_values)

[[2 1 4 0 2]
 [0 2 2 3 4]
 [4 0 2 2 4]
 [1 3 1 3 4]
 [2 1 3 2 0]]
 
[[0 3 3 4 4]
 [3 2 4 1 0]
 [2 2 4 2 3]
 [1 3 3 2 3]
 [3 2 4 1 0]]
 
[[False False False False False]
 [False  True False False False]
 [False False False  True False]
 [ True  True False False False]
 [False False False False  True]]
 
[2 2 1 3 0]
 
[0 1 2 3]


#### 31. How to ignore all numpy warnings (not recommended)? (★☆☆)

In [268]:
import warnings
warnings.filterwarnings('ignore')

# or
sup = np.testing.suppress_warnings()
sup.filter(module=np.ma.core)  # module must match exactly
@sup
def some_function():
    # do something which causes a warning in np.ma.core
    pass

#### 32. Is the following expressions true? (★☆☆)
```python
np.sqrt(-1) == np.emath.sqrt(-1)
```

In [272]:
print(np.sqrt(-1) == np.emath.sqrt(-1))
print(np.sqrt(-1))
print(np.emath.sqrt(-1))

False
nan
1j


#### 33. How to get the dates of yesterday, today and tomorrow? (★☆☆)

In [279]:
today = np.datetime64('today', 'D')
yesterday = today - np.timedelta64(1, 'D')
tomorrow = today + np.timedelta64(1, 'D')
print("Yesterday it was the", yesterday, ", today it's the", today, ", tomorrow it will be the", tomorrow)

Yesterday it was the 2020-05-24 , today it's the 2020-05-25 , tomorrow it will be the 2020-05-26


#### 34. How to get all the dates corresponding to the month of July 2016? (★★☆)

In [283]:
np.arange('2016-07', '2016-08', dtype='datetime64[D]')

array(['2016-07-01', '2016-07-02', '2016-07-03', '2016-07-04',
       '2016-07-05', '2016-07-06', '2016-07-07', '2016-07-08',
       '2016-07-09', '2016-07-10', '2016-07-11', '2016-07-12',
       '2016-07-13', '2016-07-14', '2016-07-15', '2016-07-16',
       '2016-07-17', '2016-07-18', '2016-07-19', '2016-07-20',
       '2016-07-21', '2016-07-22', '2016-07-23', '2016-07-24',
       '2016-07-25', '2016-07-26', '2016-07-27', '2016-07-28',
       '2016-07-29', '2016-07-30', '2016-07-31'], dtype='datetime64[D]')

#### 35. How to compute ((A+B)*(-A/2)) in place (without copy)? (★★☆)

In [291]:
A = np.random.randint(0,10,(3,3))
B = np.random.randint(0,10,(3,3))

print(((A+B)*(-A/2)))
print(" ")
print(np.multiply(np.add(A, B), np.divide(-A, 2)))

[[ -9.  -30.   -8. ]
 [ -9.  -44.  -13.5]
 [ -1.5 -25.  -12. ]]
 
[[ -9.  -30.   -8. ]
 [ -9.  -44.  -13.5]
 [ -1.5 -25.  -12. ]]


#### 36. Extract the integer part of a random array using 5 different methods (★★☆)

#### 37. Create a 5x5 matrix with row values ranging from 0 to 4 (★★☆)

#### 38. Consider a generator function that generates 10 integers and use it to build an array (★☆☆)

In [293]:
A = np.random.randint(0,10,(2,5))
print(A)

[[6 6 4 9 3]
 [2 1 0 0 1]]


#### 39. Create a vector of size 10 with values ranging from 0 to 1, both excluded (★★☆)

In [296]:
v = np.random.rand(10)
print(v)

## it might happen that 0 or 1 are included, fix that:
e = 0.000000001
v = (v + e) / (1 + 2*e)

[0.17553321 0.44306109 0.11140476 0.04063933 0.50785014 0.2439309
 0.70299209 0.96867901 0.12574812 0.50757487]


#### 40. Create a random vector of size 10 and sort it (★★☆)

In [300]:
v = np.random.randint(0, 10, (1, 10))
print(v)
np.sort(v)

[[2 0 3 7 7 9 0 5 2 8]]


array([[0, 0, 2, 2, 3, 5, 7, 7, 8, 9]])

#### 41. How to sum a small array faster than np.sum? (★★☆)

In [314]:
import time

A = np.random.rand(1099999)
print(A)
print(" ")

# summing with np.sum
start_time = time.time()
np.sum(A)
print(time.time() - start_time)

start_time = time.time()
sum(A)
print(time.time() - start_time)

# No idea...

[0.87619595 0.10125999 0.66193122 ... 0.38842241 0.29354872 0.12669216]
 
0.001996278762817383
0.001993417739868164


#### 42. Consider two random array A and B, check if they are equal (★★☆)

In [331]:
A = np.random.randint(0,2,(2,2))
B = np.random.randint(0,2,(2,2))
print(A)
print(B)

(A == B).all()

[[0 1]
 [1 0]]
[[0 1]
 [1 1]]


False

#### 43. Make an array immutable (read-only) (★★☆)

In [334]:
A = np.random.randint(0,2,(2,2))
A.flags.writeable = False

print(A)

A[0,0] = 9

[[1 0]
 [0 0]]


ValueError: assignment destination is read-only

#### 44. Consider a random 10x2 matrix representing cartesian coordinates, convert them to polar coordinates (★★☆)

In [340]:
A = np.random.randint(0,10,(10,2))
print(A)
def cart2pol(A):
    x, y = A[:,0], A[:,1]
    rho = np.sqrt(x**2 + y**2)
    phi = np.arctan2(y, x)
    return(rho, phi)

cart2pol(A)

[[8 6]
 [0 7]
 [3 2]
 [1 7]
 [5 2]
 [8 1]
 [6 0]
 [7 2]
 [2 9]
 [1 2]]


(array([10.        ,  7.        ,  3.60555128,  7.07106781,  5.38516481,
         8.06225775,  6.        ,  7.28010989,  9.21954446,  2.23606798]),
 array([0.64350111, 1.57079633, 0.5880026 , 1.42889927, 0.38050638,
        0.12435499, 0.        , 0.27829966, 1.35212738, 1.10714872]))

#### 45. Create random vector of size 10 and replace the maximum value by 0 (★★☆)

In [358]:
A = np.random.randint(0, 10, (5,10))
print(A)
print(" ")
A[A == A.max(axis=1)[:,np.newaxis]] = 0
print(A)

[[8 9 0 4 1 8 9 0 4 4]
 [8 3 1 8 9 7 8 0 3 7]
 [2 4 2 0 7 3 9 2 0 8]
 [4 6 3 8 0 3 3 5 3 8]
 [8 0 0 4 8 3 6 7 6 2]]
 
[[8 0 0 4 1 8 0 0 4 4]
 [8 3 1 8 0 7 8 0 3 7]
 [2 4 2 0 7 3 0 2 0 8]
 [4 6 3 0 0 3 3 5 3 0]
 [0 0 0 4 0 3 6 7 6 2]]


#### 46. Create a structured array with `x` and `y` coordinates covering the [0,1]x[0,1] area (★★☆)

#### 47. Given two arrays, X and Y, construct the Cauchy matrix C (Cij =1/(xi - yj))

#### 48. Print the minimum and maximum representable value for each numpy scalar type (★★☆)

#### 49. How to print all the values of an array? (★★☆)

In [359]:
A = np.random.randint(0, 10, (5,10))
print(A)

[[0 2 1 2 8 0 4 8 4 1]
 [1 5 9 4 1 6 8 3 1 2]
 [6 8 7 8 0 6 9 8 8 9]
 [8 9 0 9 2 4 0 6 6 7]
 [5 2 7 8 0 1 8 5 8 2]]


#### 50. How to find the closest value (to a given scalar) in a vector? (★★☆)

In [361]:
def find_closest_value(A, n):
    return (np.abs(A-n)).argmin()

n = 5.4
A = np.arange(10)
find_closest_index(A,n)

5

#### 51. Create a structured array representing a position (x,y) and a color (r,g,b) (★★☆)

#### 52. Consider a random vector with shape (100,2) representing coordinates, find point by point distances (★★☆)

#### 53. How to convert a float (32 bits) array into an integer (32 bits) in place?

#### 54. How to read the following file? (★★☆)
```
1, 2, 3, 4, 5
6,  ,  , 7, 8
 ,  , 9,10,11
```

#### 55. What is the equivalent of enumerate for numpy arrays? (★★☆)

#### 56. Generate a generic 2D Gaussian-like array (★★☆)

#### 57. How to randomly place p elements in a 2D array? (★★☆)

#### 58. Subtract the mean of each row of a matrix (★★☆)

#### 59. How to sort an array by the nth column? (★★☆)

#### 60. How to tell if a given 2D array has null columns? (★★☆)

#### 61. Find the nearest value from a given value in an array (★★☆)

#### 62. Considering two arrays with shape (1,3) and (3,1), how to compute their sum using an iterator? (★★☆)

#### 63. Create an array class that has a name attribute (★★☆)

#### 64. Consider a given vector, how to add 1 to each element indexed by a second vector (be careful with repeated indices)? (★★★)

#### 65. How to accumulate elements of a vector (X) to an array (F) based on an index list (I)? (★★★)

#### 66. Considering a (w,h,3) image of (dtype=ubyte), compute the number of unique colors (★★★)

#### 67. Considering a four dimensions array, how to get sum over the last two axis at once? (★★★)

#### 68. Considering a one-dimensional vector D, how to compute means of subsets of D using a vector S of same size describing subset  indices? (★★★)

#### 69. How to get the diagonal of a dot product? (★★★)

#### 70. Consider the vector [1, 2, 3, 4, 5], how to build a new vector with 3 consecutive zeros interleaved between each value? (★★★)

#### 71. Consider an array of dimension (5,5,3), how to mulitply it by an array with dimensions (5,5)? (★★★)

#### 72. How to swap two rows of an array? (★★★)

#### 73. Consider a set of 10 triplets describing 10 triangles (with shared vertices), find the set of unique line segments composing all the  triangles (★★★)

#### 74. Given an array C that is a bincount, how to produce an array A such that np.bincount(A) == C? (★★★)

#### 75. How to compute averages using a sliding window over an array? (★★★)

#### 76. Consider a one-dimensional array Z, build a two-dimensional array whose first row is (Z[0],Z[1],Z[2]) and each subsequent row is  shifted by 1 (last row should be (Z[-3],Z[-2],Z[-1]) (★★★)

#### 77. How to negate a boolean, or to change the sign of a float inplace? (★★★)

#### 78. Consider 2 sets of points P0,P1 describing lines (2d) and a point p, how to compute distance from p to each line i (P0[i],P1[i])? (★★★)

#### 79. Consider 2 sets of points P0,P1 describing lines (2d) and a set of points P, how to compute distance from each point j (P[j]) to each line i (P0[i],P1[i])? (★★★)

#### 80. Consider an arbitrary array, write a function that extract a subpart with a fixed shape and centered on a given element (pad with a `fill` value when necessary) (★★★)

#### 81. Consider an array Z = [1,2,3,4,5,6,7,8,9,10,11,12,13,14], how to generate an array R = [[1,2,3,4], [2,3,4,5], [3,4,5,6], ..., [11,12,13,14]]? (★★★)

#### 82. Compute a matrix rank (★★★)

#### 83. How to find the most frequent value in an array?

#### 84. Extract all the contiguous 3x3 blocks from a random 10x10 matrix (★★★)

#### 85. Create a 2D array subclass such that Z[i,j] == Z[j,i] (★★★)

#### 86. Consider a set of p matrices wich shape (n,n) and a set of p vectors with shape (n,1). How to compute the sum of of the p matrix products at once? (result has shape (n,1)) (★★★)

#### 87. Consider a 16x16 array, how to get the block-sum (block size is 4x4)? (★★★)

#### 88. How to implement the Game of Life using numpy arrays? (★★★)

#### 89. How to get the n largest values of an array (★★★)

#### 90. Given an arbitrary number of vectors, build the cartesian product (every combinations of every item) (★★★)

#### 91. How to create a record array from a regular array? (★★★)

#### 92. Consider a large vector Z, compute Z to the power of 3 using 3 different methods (★★★)

#### 93. Consider two arrays A and B of shape (8,3) and (2,2). How to find rows of A that contain elements of each row of B regardless of the order of the elements in B? (★★★)

#### 94. Considering a 10x3 matrix, extract rows with unequal values (e.g. [2,2,3]) (★★★)

#### 95. Convert a vector of ints into a matrix binary representation (★★★)

#### 96. Given a two dimensional array, how to extract unique rows? (★★★)

#### 97. Considering 2 vectors A & B, write the einsum equivalent of inner, outer, sum, and mul function (★★★)

#### 98. Considering a path described by two vectors (X,Y), how to sample it using equidistant samples (★★★)?

#### 99. Given an integer n and a 2D array X, select from X the rows which can be interpreted as draws from a multinomial distribution with n degrees, i.e., the rows which only contain integers and which sum to n. (★★★)

#### 100. Compute bootstrapped 95% confidence intervals for the mean of a 1D array X (i.e., resample the elements of an array with replacement N times, compute the mean of each sample, and then compute percentiles over the means). (★★★)